

tranch1:
        wget http://sampy.ml:499/persons-posture-tranch1.zip
        unzip persons-posture-tranch1.zip
        mv home/tyler/git/darknet/data/persons/yolo/v4/ tranch1

tranch2:
        wget http://sampy.ml:499/persons-posture-tranch2.zip
        unzip persons-posture-tranch2.zip

tranch3:
        wget http://sampy.ml:499/persons-posture-tranch3.zip
        unzip persons-posture-tranch3.zip


all: tranch1 tranch2 tranch3

clean:
      	rm -rf home
